version: "3"

services:

  mysql-db:
    image: mysql:8.0.31
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'tpfoyer'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp


  springboot-app:

    image: amiraabdrabou/tp-foyer:latest
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.50.4:3306/tpfoyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tpfoyer
    restart: on-failure
    ports:
      - 8089:8089
    links:
      - mysql-db